name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04

    steps:
      - name: Install toolchains
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            binutils-aarch64-linux-gnu \
            bc bison flex libssl-dev make \
            build-essential git

      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/riloraspopo/android_kernel_xiaomi_pipa
          config: defconfig
          arch: arm64
          abi: arm64
          android-version: 16
          ksu: true
          skip-install: true
